import { useEffect, useMemo, useState, type FormEvent } from 'react';
import AppShell from '../../components/shell/AppShell';
import { InlineError, LoadingState, SuccessNotice } from '../../components/ux/UiStates';
import { getActiveCategories, getActiveVendors, type CatalogCategory } from '../commerce/catalogApi';
import { createCouponCode, createPromotion, listPromotionsAdmin, setCouponActive, setPromotionActive, type Promotion } from '../commerce/promotionsApi';

const money = (value: number) => new Intl.NumberFormat('ku-IQ', { maximumFractionDigits: 0 }).format(value);
const label = (item: Promotion) => item.name_ckb || item.name_ar || item.name_en;

const emptyForm = { name_ckb:'', name_ar:'', name_en:'', promotion_type:'coupon' as const, discount_type:'percentage' as const, discount_value:'10', max_discount_iqd:'', min_subtotal_iqd:'0', priority:'0', usage_limit:'', per_user_limit:'1', starts_at:'', ends_at:'', vendor_id:'', category_id:'' };

export default function PromotionsPage() {
  const [items,setItems]=useState<Promotion[]>([]); const [categories,setCategories]=useState<CatalogCategory[]>([]); const [vendors,setVendors]=useState<Awaited<ReturnType<typeof getActiveVendors>>>([]);
  const [form,setForm]=useState(emptyForm); const [selectedPromo,setSelectedPromo]=useState(''); const [couponCode,setCouponCode]=useState(''); const [couponLimit,setCouponLimit]=useState(''); const [couponPerUser,setCouponPerUser]=useState('1');
  const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [success,setSuccess]=useState('');

  async function load(){ setLoading(true); setError(''); try { const [p,c,v]=await Promise.all([listPromotionsAdmin(),getActiveCategories(),getActiveVendors()]); setItems(p); setCategories(c); setVendors(v); } catch(err){setError(err instanceof Error?err.message:'promotions_load_failed');} finally{setLoading(false);} }
  useEffect(()=>{void load();},[]);
  const selected = useMemo(()=>items.find(x=>x.id===selectedPromo) ?? null,[items,selectedPromo]);

  async function submitPromotion(event:FormEvent){ event.preventDefault(); setSaving(true); setError(''); setSuccess(''); try {
    const created=await createPromotion({name_ckb:form.name_ckb,name_ar:form.name_ar,name_en:form.name_en,promotion_type:form.promotion_type,discount_type:form.discount_type,discount_value:Number(form.discount_value),max_discount_iqd:form.max_discount_iqd?Number(form.max_discount_iqd):null,min_subtotal_iqd:Number(form.min_subtotal_iqd||0),priority:Number(form.priority||0),usage_limit:form.usage_limit?Number(form.usage_limit):null,per_user_limit:Number(form.per_user_limit||1),vendor_id:form.vendor_id||null,category_id:form.category_id||null,starts_at:form.starts_at?new Date(form.starts_at).toISOString():undefined,ends_at:form.ends_at?new Date(form.ends_at).toISOString():null});
    setSuccess('پرۆمۆشن بە سەرکەوتوویی دروست کرا.'); setForm(emptyForm); setSelectedPromo(created.id); await load();
  }catch(err){setError(err instanceof Error?err.message:'promotion_create_failed');}finally{setSaving(false);} }
  async function submitCoupon(event:FormEvent){event.preventDefault(); if(!selectedPromo||!couponCode.trim())return; setSaving(true);setError('');setSuccess('');try{await createCouponCode(selectedPromo,couponCode,couponLimit?Number(couponLimit):null,Number(couponPerUser||1));setCouponCode('');setSuccess('کۆدی coupon دروست کرا.');await load();}catch(err){setError(err instanceof Error?err.message:'coupon_create_failed');}finally{setSaving(false);}}
  async function togglePromotion(item:Promotion){setSaving(true);setError('');try{await setPromotionActive(item.id,!item.is_active);await load();}catch(err){setError(err instanceof Error?err.message:'promotion_toggle_failed');}finally{setSaving(false);}}
  async function toggleCoupon(coupon:NonNullable<Promotion['coupons']>[number]){setSaving(true);setError('');try{await setCouponActive(coupon.id,!coupon.is_active);await load();}catch(err){setError(err instanceof Error?err.message:'coupon_toggle_failed');}finally{setSaving(false);}}

  return <AppShell><main dir="rtl" className="space-y-5">
    <section className="rounded-[30px] bg-slate-950 p-6 text-white shadow-[var(--shakh-shadow-md)] sm:p-8"><p className="text-[10px] font-black tracking-[0.18em] text-orange-300">PROMOTIONS CENTER</p><h1 className="mt-2 text-3xl font-black">پرۆمۆشن و coupon ـەکان</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-white/60">هەموو discount ـەکان لە database ـەوەن؛ validation، usage limit و checkout total لە server کۆنترۆڵ دەکرێن.</p></section>
    {error&&<InlineError title="Promotion کێشەی هەیە" body={error}/>} {success&&<SuccessNotice title="سەرکەوتوو" body={success}/>} {loading?<LoadingState label="پرۆمۆشنەکان بار دەکرێن..."/>:null}
    <div className="grid gap-5 xl:grid-cols-[1fr_.9fr]">
      <form onSubmit={submitPromotion} className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-[var(--shakh-shadow-sm)] sm:p-7 space-y-4">
        <div><p className="text-[10px] font-black tracking-[0.18em] text-orange-600">NEW CAMPAIGN</p><h2 className="mt-1 text-xl font-black">دروستکردنی پرۆمۆشن</h2></div>
        <div className="grid gap-3 sm:grid-cols-3">{(['name_ckb','name_ar','name_en'] as const).map((key)=><input key={key} required className="min-h-11 rounded-2xl border border-slate-200 bg-slate-50 px-4 text-sm font-bold outline-none focus:border-orange-400 focus:bg-white" placeholder={key==='name_ckb'?'ناوی کوردی':key==='name_ar'?'الاسم العربي':'English name'} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/>)}</div>
        <div className="grid gap-3 sm:grid-cols-2"><select className="min-h-11 rounded-2xl border border-slate-200 bg-slate-50 px-4 text-sm font-bold" value={form.promotion_type} onChange={e=>setForm({...form,promotion_type:e.target.value as typeof form.promotion_type})}><option value="coupon">Coupon code</option><option value="automatic">Automatic</option></select><select className="min-h-11 rounded-2xl border border-slate-200 bg-slate-50 px-4 text-sm font-bold" value={form.discount_type} onChange={e=>setForm({...form,discount_type:e.target.value as typeof form.discount_type})}><option value="percentage">Percentage %</option><option value="fixed">Fixed IQD</option></select></div>
        <div className="grid gap-3 sm:grid-cols-3"><input required type="number" min="0" step="0.01" className="min-h-11 rounded-2xl border border-slate-200 bg-slate-50 px-4 text-sm font-bold" placeholder="discount value" value={form.discount_value} onChange={e=>setForm({...form,discount_value:e.target.value})}/><input type="number" min="0" step="1" className="min-h-11 rounded-2xl border border-slate-200 bg-slate-50 px-4 text-sm font-bold" placeholder="max discount IQD" value={form.max_discount_iqd} onChange={e=>setForm({...form,max_discount_iqd:e.target.value})}/><input type="number" min="0" step="1" className="min-h-11 rounded-2xl border border-slate-200 bg-slate-50 px-4 text-sm font-bold" placeholder="minimum subtotal" value={form.min_subtotal_iqd} onChange={e=>setForm({...form,min_subtotal_iqd:e.target.value})}/></div>
        <div className="grid gap-3 sm:grid-cols-2"><select className="min-h-11 rounded-2xl border border-slate-200 bg-slate-50 px-4 text-sm font-bold" value={form.vendor_id} onChange={e=>setForm({...form,vendor_id:e.target.value})}><option value="">هەموو فرۆشیاران</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.name_ckb||v.name_ar||v.name_en}</option>)}</select><select className="min-h-11 rounded-2xl border border-slate-200 bg-slate-50 px-4 text-sm font-bold" value={form.category_id} onChange={e=>setForm({...form,category_id:e.target.value})}><option value="">هەموو کاتەلۆگ</option>{categories.map(c=><option key={c.id} value={c.id}>{c.nameCkb||c.nameAr||c.nameEn}</option>)}</select></div>
        <div className="grid gap-3 sm:grid-cols-4"><input type="number" min="0" className="min-h-11 rounded-2xl border border-slate-200 bg-slate-50 px-4 text-sm font-bold" placeholder="priority" value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}/><input type="number" min="1" className="min-h-11 rounded-2xl border border-slate-200 bg-slate-50 px-4 text-sm font-bold" placeholder="per user" value={form.per_user_limit} onChange={e=>setForm({...form,per_user_limit:e.target.value})}/><input type="number" min="1" className="min-h-11 rounded-2xl border border-slate-200 bg-slate-50 px-4 text-sm font-bold" placeholder="usage cap" value={form.usage_limit} onChange={e=>setForm({...form,usage_limit:e.target.value})}/><button disabled={saving} className="shakh-btn-primary">{saving?'تۆمار دەکرێت...':'دروستکردنی campaign'}</button></div>
      </form>
      <form onSubmit={submitCoupon} className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-[var(--shakh-shadow-sm)] sm:p-7 space-y-4"><div><p className="text-[10px] font-black tracking-[0.18em] text-orange-600">COUPON CODE</p><h2 className="mt-1 text-xl font-black">زیادکردنی کۆد</h2></div><select required className="min-h-11 w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 text-sm font-bold" value={selectedPromo} onChange={e=>setSelectedPromo(e.target.value)}><option value="">پرۆمۆشن هەڵبژێرە</option>{items.filter(i=>i.promotion_type==='coupon').map(i=><option key={i.id} value={i.id}>{label(i)}</option>)}</select><input required minLength={3} maxLength={64} className="min-h-11 w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 text-sm font-bold uppercase" placeholder="مثلاً SHAKH10" value={couponCode} onChange={e=>setCouponCode(e.target.value.toUpperCase())}/><div className="grid gap-3 sm:grid-cols-2"><input type="number" min="1" className="min-h-11 rounded-2xl border border-slate-200 bg-slate-50 px-4 text-sm font-bold" placeholder="usage cap" value={couponLimit} onChange={e=>setCouponLimit(e.target.value)}/><input type="number" min="1" className="min-h-11 rounded-2xl border border-slate-200 bg-slate-50 px-4 text-sm font-bold" placeholder="per user" value={couponPerUser} onChange={e=>setCouponPerUser(e.target.value)}/></div><button disabled={saving||!selectedPromo} className="min-h-11 w-full rounded-2xl bg-slate-950 px-5 text-sm font-black text-white disabled:opacity-50">دروستکردنی coupon</button>{selected?<p className="rounded-2xl bg-slate-50 p-4 text-xs leading-6 text-slate-500">هەڵبژێردراو: <b className="text-slate-900">{label(selected)}</b><br/>discount: {selected.discount_type==='percentage'?`${selected.discount_value}%`:`${money(selected.discount_value)} د.ع`}</p>:null}</form>
    </div>
    <section className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-[var(--shakh-shadow-sm)] sm:p-7"><div className="flex items-end justify-between gap-3"><div><p className="text-[10px] font-black tracking-[0.18em] text-orange-600">LIVE CAMPAIGNS</p><h2 className="mt-1 text-xl font-black">هەموو campaign ـەکان</h2></div><button type="button" onClick={()=>void load()} className="rounded-2xl border border-slate-200 px-4 py-2 text-xs font-black text-slate-600">نوێکردنەوە</button></div>{!items.length&&!loading?<p className="mt-5 rounded-2xl bg-slate-50 p-6 text-center text-sm font-bold text-slate-500">هێشتا promotion ـێک دروست نەکراوە.</p>:<div className="mt-5 space-y-3">{items.map(item=><div key={item.id} className="rounded-2xl border border-slate-100 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-black text-slate-950">{label(item)}</p><p className="mt-1 text-[11px] text-slate-400">{item.promotion_type} · {item.discount_type==='percentage'?`${item.discount_value}%`:`${money(item.discount_value)} د.ع`}</p></div><button type="button" disabled={saving} onClick={()=>void togglePromotion(item)} className={`rounded-xl px-3 py-2 text-[10px] font-black ${item.is_active?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{item.is_active?'ACTIVE':'INACTIVE'}</button></div>{item.coupons?.length?<div className="mt-3 flex flex-wrap gap-2">{item.coupons.map(c=><button key={c.id} type="button" disabled={saving} onClick={()=>void toggleCoupon(c)} className={`rounded-xl border px-3 py-2 text-[10px] font-black ${c.is_active?'border-orange-200 bg-orange-50 text-orange-700':'border-slate-200 bg-slate-50 text-slate-400'}`}>{c.code} · {c.usage_count}/{c.usage_limit??'∞'}</button>)}</div>:null}</div>)}</div>}</section>
  </main></AppShell>;
}
