import { useEffect, useState } from 'react';
import AppShell from '../../components/shell/AppShell';
import {
  createDeliveryZone,
  createDispatchRule,
  formatIqd,
  getDeliveryPricingAdmin,
  type DeliveryZone,
  type DispatchRule,
  updateDeliveryZone,
  updateDispatchRule,
} from '../commerce/deliveryPricingApi';

const emptyZone: Omit<DeliveryZone,'id'|'created_at'|'updated_at'> = {
  code:'', name_ckb:'', name_ar:'', name_en:'', city:'هەولێر', district:null,
  center_latitude:null, center_longitude:null, radius_km:5, priority:0, base_fee_iqd:0,
  included_km:0, per_km_fee_iqd:0, min_fee_iqd:0, max_fee_iqd:null, surge_multiplier:1,
  free_delivery_threshold_iqd:null, estimated_base_minutes:20, estimated_per_km_minutes:4,
  is_active:true,
};
const emptyRule: Omit<DispatchRule,'id'|'created_at'|'updated_at'> = {
  name_ckb:'', name_en:'', priority:0, vehicle_type:null, max_pickup_distance_km:null,
  max_location_age_seconds:180, min_sla_remaining_minutes:null, require_gps:false, allow_no_gps:true,
  is_active:true,
};

export default function DeliveryPricingPage(){
  const [zones,setZones]=useState<DeliveryZone[]>([]),[rules,setRules]=useState<DispatchRule[]>([]);
  const [zone,setZone]=useState(emptyZone),[rule,setRule]=useState(emptyRule);
  const [editingZone,setEditingZone]=useState<string|null>(null),[editingRule,setEditingRule]=useState<string|null>(null);
  const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
  const load=async()=>{setLoading(true);try{const d=await getDeliveryPricingAdmin();setZones(d.zones);setRules(d.rules);setError('')}catch(e){setError(e instanceof Error?e.message:'pricing_load_failed')}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  const saveZone=async()=>{setSaving(true);setError('');setMessage('');try{if(!zone.code||!zone.name_ckb||!zone.name_ar||!zone.name_en||!zone.city){throw new Error('code، ناو، city پێویستن')}if(editingZone)await updateDeliveryZone(editingZone,zone);else await createDeliveryZone(zone);setZone(emptyZone);setEditingZone(null);setMessage('Delivery Zone بە سەرکەوتوویی پاشەکەوت کرا.');await load()}catch(e){setError(e instanceof Error?e.message:'zone_save_failed')}finally{setSaving(false)}};
  const saveRule=async()=>{setSaving(true);setError('');setMessage('');try{if(!rule.name_ckb||!rule.name_en){throw new Error('ناوی rule پێویستە')}if(editingRule)await updateDispatchRule(editingRule,rule);else await createDispatchRule(rule);setRule(emptyRule);setEditingRule(null);setMessage('Dispatch Rule بە سەرکەوتوویی پاشەکەوت کرا.');await load()}catch(e){setError(e instanceof Error?e.message:'rule_save_failed')}finally{setSaving(false)}};
  return <AppShell><main dir="rtl" className="mx-auto max-w-[1280px] space-y-5">
    <section className="rounded-[30px] border border-slate-200 bg-white p-6 shadow-[var(--shakh-shadow-sm)] sm:p-8"><p className="text-[10px] font-black tracking-[.18em] text-orange-600">DELIVERY ENGINE</p><h1 className="mt-2 text-3xl font-black tracking-tight text-slate-950">Zone و نرخی گەیاندن</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-slate-500">نرخی گەیاندن لە server ـەوە حیساب دەکرێت: base fee + distance + surge + cap/minimum، و دوای checkout لە order ـدا snapshot دەکرێت.</p></section>
    {error&&<div role="alert" className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-bold text-rose-700">{error}</div>}{message&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-700">{message}</div>}
    <section className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]">
      <div className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-[var(--shakh-shadow-sm)]"><div className="flex items-end justify-between gap-3"><div><p className="text-[10px] font-black tracking-[.16em] text-orange-600">ZONES</p><h2 className="mt-1 text-xl font-black">Delivery Zones</h2></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black">{zones.length}</span></div><div className="mt-5 space-y-2">{loading?<p className="p-5 text-sm text-slate-400">بارکردن...</p>:zones.map(z=><article key={z.id} className="rounded-2xl border border-slate-100 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><strong className="text-sm font-black">{z.name_ckb}</strong><p className="mt-1 text-xs text-slate-400">{z.code} · {z.city}{z.district?` · ${z.district}`:''}</p></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${z.is_active?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{z.is_active?'چالاک':'ناچالاک'}</span></div><div className="mt-3 grid grid-cols-2 gap-2 text-xs sm:grid-cols-4"><span className="rounded-xl bg-slate-50 p-2"><b>Base</b><br/>{formatIqd(Number(z.base_fee_iqd))}</span><span className="rounded-xl bg-slate-50 p-2"><b>Km</b><br/>{formatIqd(Number(z.per_km_fee_iqd))}</span><span className="rounded-xl bg-slate-50 p-2"><b>Radius</b><br/>{z.radius_km} km</span><span className="rounded-xl bg-slate-50 p-2"><b>Surge</b><br/>{z.surge_multiplier}×</span></div><button className="mt-3 rounded-xl border border-slate-200 px-3 py-2 text-xs font-black" onClick={()=>{setZone({...z});setEditingZone(z.id)}}>دەستکاری</button></article>)}</div></div>
      <div className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-[var(--shakh-shadow-sm)]"><p className="text-[10px] font-black tracking-[.16em] text-orange-600">ZONE EDITOR</p><h2 className="mt-1 text-xl font-black">{editingZone?'نوێکردنەوەی zone':'Zone ـێکی نوێ'}</h2><div className="mt-4 grid gap-2 sm:grid-cols-2">{([['code','Code'],['name_ckb','ناوی کوردی'],['name_ar','عەرەبی'],['name_en','English'],['city','City'],['district','District'],['center_latitude','Latitude'],['center_longitude','Longitude'],['radius_km','Radius km'],['priority','Priority'],['base_fee_iqd','Base IQD'],['included_km','Included km'],['per_km_fee_iqd','Per km IQD'],['min_fee_iqd','Min fee'],['max_fee_iqd','Max fee'],['surge_multiplier','Surge'],['free_delivery_threshold_iqd','Free threshold'],['estimated_base_minutes','Base ETA'],['estimated_per_km_minutes','ETA / km']] as const).map(([key,label])=><label className="text-xs font-bold text-slate-500" key={key}>{label}<input value={zone[key]??''} onChange={e=>setZone(v=>({...v,[key]:e.target.value===''?null:Number.isNaN(Number(e.target.value))?e.target.value:Number(e.target.value)} as typeof v))} className="mt-1 min-h-10 w-full rounded-xl border border-slate-200 px-3 text-sm font-black outline-none focus:border-orange-400" /></label>)}</div><label className="mt-3 flex items-center gap-2 text-xs font-black"><input type="checkbox" checked={zone.is_active} onChange={e=>setZone(v=>({...v,is_active:e.target.checked}))}/> zone چالاک بێت</label><div className="mt-4 flex gap-2"><button className="shakh-btn-primary flex-1" disabled={saving} onClick={()=>void saveZone()}>{saving?'...':'پاشەکەوتکردن'}</button>{editingZone&&<button className="rounded-2xl border border-slate-200 px-4 text-xs font-black" onClick={()=>{setEditingZone(null);setZone(emptyZone)}}>Cancel</button>}</div></div>
    </section>
    <section className="grid gap-5 xl:grid-cols-[1fr_.7fr]"><div className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-[var(--shakh-shadow-sm)]"><p className="text-[10px] font-black tracking-[.16em] text-orange-600">DISPATCH RULES</p><h2 className="mt-1 text-xl font-black">Advanced Dispatch Rules</h2><div className="mt-5 space-y-2">{rules.map(r=><article key={r.id} className="rounded-2xl border border-slate-100 p-4"><div className="flex items-center justify-between gap-3"><div><strong className="text-sm font-black">{r.name_ckb}</strong><p className="mt-1 text-xs text-slate-400">Priority {r.priority} · {r.vehicle_type??'هەموو ئۆتۆمبێل'} · GPS ≤ {r.max_location_age_seconds}s</p></div><button className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-black" onClick={()=>{setEditingRule(r.id);setRule({...r})}}>دەستکاری</button></div></article>)}</div></div><div className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-[var(--shakh-shadow-sm)]"><p className="text-[10px] font-black tracking-[.16em] text-orange-600">RULE EDITOR</p><h2 className="mt-1 text-xl font-black">{editingRule?'نوێکردنەوەی rule':'Rule ـێکی نوێ'}</h2><div className="mt-4 grid gap-2">{([['name_ckb','ناوی کوردی'],['name_en','English'],['priority','Priority'],['vehicle_type','Vehicle type'],['max_pickup_distance_km','Max pickup km'],['max_location_age_seconds','GPS age seconds'],['min_sla_remaining_minutes','Min SLA minutes']] as const).map(([key,label])=><label className="text-xs font-bold text-slate-500" key={key}>{label}<input value={rule[key]??''} onChange={e=>setRule(v=>({...v,[key]:e.target.value===''?null:Number.isNaN(Number(e.target.value))?e.target.value:Number(e.target.value)} as typeof v))} className="mt-1 min-h-10 w-full rounded-xl border border-slate-200 px-3 text-sm font-black outline-none focus:border-orange-400" /></label>)}{[['require_gps','GPS پێویستە'],['allow_no_gps','بێ GPS ڕێگەپێدراوە'],['is_active','rule چالاکە']].map(([key,label])=><label key={key} className="flex items-center gap-2 text-xs font-black"><input type="checkbox" checked={Boolean(rule[key as keyof typeof rule])} onChange={e=>setRule(v=>({...v,[key]:e.target.checked}))}/>{label}</label>)}</div><div className="mt-4 flex gap-2"><button className="shakh-btn-primary flex-1" disabled={saving} onClick={()=>void saveRule()}>{saving?'...':'پاشەکەوتکردن'}</button>{editingRule&&<button className="rounded-2xl border border-slate-200 px-4 text-xs font-black" onClick={()=>{setEditingRule(null);setRule(emptyRule)}}>Cancel</button>}</div></div></section>
  </main></AppShell>;
}
