import { useEffect, useState, type FormEvent } from 'react';
import AppShell from '../../components/shell/AppShell';
import { LoadingState } from '../../components/ux/UiStates';
import { useAuth } from '../auth/AuthContext';
import { createUmrahBooking, createUmrahPackage, getUmrahBookingFee, listUmrahPackages, type UmrahPackage } from './umrahApi';

const money = (value: number) => `${new Intl.NumberFormat('ku-IQ', { maximumFractionDigits: 0 }).format(value)} IQD`;

export default function UmrahPage() {
  const { user, roles } = useAuth();
  const isAgency = roles.includes('umrah_agency');
  const [packages, setPackages] = useState<UmrahPackage[]>([]);
  const [fee, setFee] = useState(2000);
  const [loading, setLoading] = useState(true);
  const [selected, setSelected] = useState<UmrahPackage | null>(null);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  const [contact, setContact] = useState({ name: '', phone: '', count: 1, notes: '' });
  const [agencyOpen, setAgencyOpen] = useState(false);
  const [agencyForm, setAgencyForm] = useState({ title: '', departure: '', returnDate: '', duration: '', hotel: '', transport: '', packagePrice: '', capacity: '', description: '' });

  const refresh = async () => { setLoading(true); setError(''); try { const [rows, currentFee] = await Promise.all([listUmrahPackages(), getUmrahBookingFee()]); setPackages(rows); setFee(currentFee); } catch (caught) { setError(caught instanceof Error ? caught.message : 'بارکردنی پەکیجی عومرە سەرکەوتوو نەبوو.'); } finally { setLoading(false); } };
  useEffect(() => { void refresh(); }, []);

  async function book(event: FormEvent) {
    event.preventDefault();
    if (!user) { window.location.hash = '#auth/sign-in'; return; }
    if (!selected) return;
    setBusy(true); setError(''); setMessage('');
    try { await createUmrahBooking({ packageId: selected.id, participantCount: contact.count, contactName: contact.name, contactPhone: contact.phone, notes: contact.notes }); setMessage(`حجزەکەت تۆمار کرا. تەنها ${money(fee)} کرێی حجز لە SHAKH دراوە؛ نرخی پەکیج لەم flow ـەدا وەرناگیرێت.`); setSelected(null); setContact({ name: '', phone: '', count: 1, notes: '' }); await refresh(); }
    catch (caught) { setError(caught instanceof Error ? caught.message : 'حجز سەرکەوتوو نەبوو.'); }
    finally { setBusy(false); }
  }

  async function createPackage(event: FormEvent) {
    event.preventDefault(); setBusy(true); setError('');
    try { await createUmrahPackage({ titleCkb: agencyForm.title, titleAr: agencyForm.title, titleEn: agencyForm.title, departureDate: agencyForm.departure || undefined, returnDate: agencyForm.returnDate || undefined, durationDays: agencyForm.duration ? Number(agencyForm.duration) : undefined, hotelName: agencyForm.hotel || undefined, transportDetails: agencyForm.transport || undefined, packagePriceIqd: agencyForm.packagePrice ? Number(agencyForm.packagePrice) : undefined, capacity: agencyForm.capacity ? Number(agencyForm.capacity) : undefined, descriptionCkb: agencyForm.description || undefined }); setAgencyForm({ title: '', departure: '', returnDate: '', duration: '', hotel: '', transport: '', packagePrice: '', capacity: '', description: '' }); setAgencyOpen(false); setMessage('پەکیجەکەت وەک draft دروست کرا. دەتوانرێت پاش پشکنین active بکرێت.'); }
    catch (caught) { setError(caught instanceof Error ? caught.message : 'دروستکردنی پەکیج سەرکەوتوو نەبوو.'); } finally { setBusy(false); }
  }

  return <AppShell><main dir="rtl" className="space-y-6">
    <section className="overflow-hidden rounded-[32px] border border-emerald-100 bg-gradient-to-br from-emerald-50 via-white to-orange-50 px-5 py-7 shadow-[var(--shakh-shadow-sm)] sm:px-8 sm:py-9"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-black tracking-[.18em] text-emerald-700">SHAKH UMRAH</p><h1 className="mt-3 text-3xl font-black tracking-tight text-slate-950 sm:text-4xl">عومرە لە SHAKH = تەنها حجز</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-600">لە SHAKH نرخی تەواوی پەکیج وەک purchase و checkout وەرناگیرێت. کڕیار تەنها کرێی حجز دەدات و agency دواتر زانیاری و پەیکەجەکە تەواو دەکات.</p></div><div className="rounded-2xl border border-orange-200 bg-white/85 p-4"><p className="text-[9px] font-black tracking-[.16em] text-orange-600">BOOKING FEE</p><strong className="mt-2 block text-xl text-slate-950">{money(fee)}</strong><span className="mt-1 block text-[10px] text-slate-500">کرێی حجز — نەک نرخی پەکیج.</span></div></div>{isAgency && <button onClick={() => setAgencyOpen(true)} className="mt-6 shakh-btn-primary" type="button">+ دروستکردنی پەکیجی عومرە</button>}</section>
    {message && <div className="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-800">{message}</div>}{error && <div className="rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-bold text-rose-800">{error}</div>}
    {loading ? <LoadingState label="پەکیجەکانی عومرە بار دەکرێن..." /> : <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{!packages.length ? <div className="col-span-full rounded-[28px] border border-dashed border-slate-300 bg-white p-10 text-center text-sm font-bold text-slate-500">هێشتا هیچ پەکیجێکی active نییە.</div> : packages.map((pkg) => <article key={pkg.id} className="rounded-[26px] border border-slate-200 bg-white p-5 shadow-[var(--shakh-shadow-sm)]"><div className="flex items-start justify-between gap-3"><div><p className="text-[9px] font-black tracking-[.16em] text-emerald-700">UMRAH PACKAGE</p><h2 className="mt-1 text-lg font-black text-slate-950">{pkg.title_ckb}</h2></div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-black text-emerald-700">حجز</span></div><div className="mt-4 grid grid-cols-2 gap-2 text-xs font-bold text-slate-600"><span className="rounded-2xl bg-slate-50 p-3">ڕۆژی دەستپێک<br/><strong className="text-slate-950">{pkg.departure_date ?? 'دیاریکراو نییە'}</strong></span><span className="rounded-2xl bg-slate-50 p-3">ماوە<br/><strong className="text-slate-950">{pkg.duration_days ? `${pkg.duration_days} ڕۆژ` : '—'}</strong></span><span className="rounded-2xl bg-slate-50 p-3">هۆتێل<br/><strong className="text-slate-950">{pkg.hotel_name ?? '—'}</strong></span><span className="rounded-2xl bg-slate-50 p-3">شار<br/><strong className="text-slate-950">{pkg.city}</strong></span></div>{pkg.package_price_iqd != null && <p className="mt-4 text-xs font-bold text-slate-500">نرخی پەکیج: <span className="text-slate-900">{money(Number(pkg.package_price_iqd))}</span> — لە SHAKH وەرناگیرێت.</p>}<button type="button" className="mt-5 w-full rounded-2xl bg-slate-950 min-h-11 px-4 text-xs font-black text-white" onClick={() => setSelected(pkg)}>حجزی ئەم پەکیجە</button></article>)}</section>}

    {selected && <div className="fixed inset-0 z-[70] grid place-items-end bg-slate-950/35 p-3 backdrop-blur-sm sm:place-items-center"><section className="w-full max-w-lg rounded-[30px] bg-white p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-black tracking-[.16em] text-emerald-700">BOOKING ONLY</p><h2 className="mt-2 text-2xl font-black">حجزی {selected.title_ckb}</h2><p className="mt-2 text-xs leading-6 text-slate-500">کرێی حجز: <strong className="text-orange-700">{money(fee)}</strong>. نرخی پەکیج دواتر لەگەڵ agency ڕێکدەخرێت.</p></div><button className="shakh-icon-button" type="button" onClick={() => setSelected(null)} aria-label="داخستن">×</button></div><form onSubmit={book} className="mt-5 grid gap-4"><Field label="ناوی پەیوەندی" value={contact.name} onChange={(v) => setContact((x) => ({ ...x, name: v }))} required /><Field label="ژمارەی مۆبایل" value={contact.phone} onChange={(v) => setContact((x) => ({ ...x, phone: v }))} required /><Field label="ژمارەی بەشداربووان" type="number" value={String(contact.count)} onChange={(v) => setContact((x) => ({ ...x, count: Math.max(1, Number(v)) }))} required /><label className="grid gap-2"><span className="text-xs font-black text-slate-700">تێبینی</span><textarea rows={3} value={contact.notes} onChange={(e) => setContact((x) => ({ ...x, notes: e.target.value }))} className="rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm outline-none" /></label><button className="shakh-btn-primary" type="submit" disabled={busy}>{busy ? 'لە حجز و پارەدان...' : `پارەدانی ${money(fee)} و حجز`}</button></form></section></div>}

    {agencyOpen && <div className="fixed inset-0 z-[70] grid place-items-end bg-slate-950/35 p-3 backdrop-blur-sm sm:place-items-center"><section className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-[30px] bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-[10px] font-black tracking-[.16em] text-orange-600">AGENCY CENTER</p><h2 className="mt-2 text-2xl font-black">پەکیجی نوێی عومرە</h2></div><button className="shakh-icon-button" type="button" onClick={() => setAgencyOpen(false)}>×</button></div><form onSubmit={createPackage} className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="ناوی پەکیج" value={agencyForm.title} onChange={(v) => setAgencyForm((x) => ({ ...x, title: v }))} required className="sm:col-span-2" /><Field label="دەستپێک" type="date" value={agencyForm.departure} onChange={(v) => setAgencyForm((x) => ({ ...x, departure: v }))} /><Field label="گەڕانەوە" type="date" value={agencyForm.returnDate} onChange={(v) => setAgencyForm((x) => ({ ...x, returnDate: v }))} /><Field label="ژمارەی ڕۆژ" type="number" value={agencyForm.duration} onChange={(v) => setAgencyForm((x) => ({ ...x, duration: v }))} /><Field label="capacity" type="number" value={agencyForm.capacity} onChange={(v) => setAgencyForm((x) => ({ ...x, capacity: v }))} /><Field label="هۆتێل" value={agencyForm.hotel} onChange={(v) => setAgencyForm((x) => ({ ...x, hotel: v }))} /><Field label="نرخی پەکیج" type="number" value={agencyForm.packagePrice} onChange={(v) => setAgencyForm((x) => ({ ...x, packagePrice: v }))} /><Field label="گەیاندن / transport" value={agencyForm.transport} onChange={(v) => setAgencyForm((x) => ({ ...x, transport: v }))} className="sm:col-span-2" /><label className="grid gap-2 sm:col-span-2"><span className="text-xs font-black text-slate-700">وەسف</span><textarea rows={4} value={agencyForm.description} onChange={(e) => setAgencyForm((x) => ({ ...x, description: e.target.value }))} className="rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm outline-none" /></label><button className="shakh-btn-primary sm:col-span-2" disabled={busy} type="submit">دروستکردنی draft</button></form></section></div>}
  </main></AppShell>;
}

function Field({ label, value, onChange, required, type='text', className='' }: { label: string; value: string; onChange: (value: string) => void; required?: boolean; type?: string; className?: string }) { return <label className={`grid gap-2 ${className}`}><span className="text-xs font-black text-slate-700">{label}</span><input required={required} type={type} value={value} onChange={(e) => onChange(e.target.value)} className="min-h-11 rounded-2xl border border-slate-200 bg-slate-50 px-4 text-sm font-semibold outline-none focus:border-orange-300 focus:bg-white" /></label>; }
