import { useEffect, useMemo, useState } from 'react';
import AppShell from '../../components/shell/AppShell';
import { useAuth } from '../auth/AuthContext';
import { createRoleApplication, listRoleApplications, reviewRoleApplication, type RoleApplication } from './roleApplicationsApi';

const roles = [
  ['captain','کاپتن','گەیاندن و ئۆردەر'],['captain_manager','بەڕێوەبەری کاپتن','چاودێری تیمی delivery'],['restaurant_vendor','فرۆشیاری ڕێستۆران','کاتەلۆگ و ئۆردەر'],['supermarket_vendor','فرۆشیاری سوپەرمارکێت','کاتەلۆگ و stock'],['fashion_vendor','فرۆشیاری فاشن','کاتەلۆگ و فروش'],['car_dealer','کار دێلەر','بازاری ئۆتۆمبێل'],['umrah_agency','ئێجەنسی عومرە','پەکیج و حجز'],['beauty_vendor','فرۆشیاری جوانکاری','کاتەلۆگ و service'],['support','پشتیوانی','تیکەت و customer care'],
] as const;

export default function RoleAccountsPage() {
  const { roles: currentRoles, hasPermission } = useAuth();
  const canReview = hasPermission('role_applications.read') || hasPermission('roles.manage');
  const [rows, setRows] = useState<RoleApplication[]>([]);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  const [noteRole, setNoteRole] = useState<string | null>(null);
  const [note, setNote] = useState('');

  async function refresh() { setError(''); try { setRows(await listRoleApplications()); } catch (caught) { setError(caught instanceof Error ? caught.message : 'بارکردنی داواکارییەکان سەرکەوتوو نەبوو.'); } }
  useEffect(() => { void refresh(); }, []);

  const statusByRole = useMemo(() => new Map(rows.map((row) => [row.requested_role, row])), [rows]);

  async function apply(role: string) { setBusy(true); setMessage(''); setError(''); try { await createRoleApplication(role, note); setNoteRole(null); setNote(''); setMessage('داواکارییەکەت تۆمار کرا و بۆ پشکنینی admin نێردرا.'); await refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'تۆمارکردنی داواکاری سەرکەوتوو نەبوو.'); } finally { setBusy(false); } }
  async function review(id: string, status: 'approved' | 'rejected') { setBusy(true); setError(''); try { await reviewRoleApplication(id, status); await refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'پشکنینی داواکاری سەرکەوتوو نەبوو.'); } finally { setBusy(false); } }

  return <AppShell><main dir="rtl" className="space-y-6"><section className="rounded-[30px] border border-slate-200 bg-white p-6 shadow-[var(--shakh-shadow-sm)] sm:p-8"><p className="text-[10px] font-black tracking-[.18em] text-orange-600">ROLE ACCOUNT CENTER</p><h1 className="mt-2 text-3xl font-black">هەژماری هەموو ڕۆڵەکان</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-slate-500">هەموو sign-up ـە نوێکان بە شێوەی خۆکار کڕیارن. بۆ ڕۆڵی کارگێڕی/پیشەیی، هەژمار دروست دەکرێت و دواتر role request دەکرێت؛ ئەمە ڕێگری دەکات لە self-escalation بۆ admin و super admin.</p><div className="mt-5 flex flex-wrap gap-2">{currentRoles.map((role) => <span key={role} className="rounded-full bg-emerald-50 px-3 py-1.5 text-[10px] font-black text-emerald-700">{role}</span>)}</div></section>
  {message && <div className="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-800">{message}</div>}{error && <div className="rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-bold text-rose-800">{error}</div>}
  <section className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{roles.map(([code,label,description]) => { const row=statusByRole.get(code); const already=currentRoles.includes(code); return <article key={code} className="rounded-[24px] border border-slate-200 bg-white p-5 shadow-[var(--shakh-shadow-sm)]"><div className="flex items-start justify-between gap-3"><div><p className="text-[9px] font-black tracking-[.14em] text-slate-400">{code}</p><h2 className="mt-1 text-base font-black text-slate-950">{label}</h2><p className="mt-1 text-xs leading-6 text-slate-500">{description}</p></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[9px] font-black text-slate-600">{already ? 'چالاک' : row?.status === 'requested' ? 'لە پشکنین' : row?.status === 'approved' ? 'پەسەندکراو' : 'ئامادەی داواکاری'}</span></div><div className="mt-4">{already ? <span className="text-xs font-black text-emerald-700">ئەم ڕۆڵە لە هەژمارەکەت چالاکە.</span> : row?.status === 'requested' ? <span className="text-xs font-bold text-orange-700">داواکارییەکەت لەلایەن admin پشکنین دەکرێت.</span> : <button disabled={busy} className="shakh-btn-primary w-full" type="button" onClick={() => { setNoteRole(code); setNote(''); }}>داوای ئەم ڕۆڵە بکە</button>}</div></article>; })}</section>
  {canReview && <section className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-[var(--shakh-shadow-sm)]"><div className="flex items-end justify-between gap-3"><div><p className="text-[10px] font-black tracking-[.16em] text-orange-600">ADMIN QUEUE</p><h2 className="mt-1 text-xl font-black">داواکارییە چاوەڕوانەکان</h2></div></div><div className="mt-4 grid gap-3">{rows.filter((r)=>r.status==='requested').length ? rows.filter((r)=>r.status==='requested').map((row)=><div key={row.id} className="flex flex-col gap-3 rounded-2xl border border-slate-100 bg-slate-50 p-4 sm:flex-row sm:items-center sm:justify-between"><div><strong className="block text-sm">{row.requested_role}</strong><span className="text-xs text-slate-500">User: {row.applicant_user_id}</span>{row.note && <p className="mt-1 text-xs text-slate-600">{row.note}</p>}</div><div className="flex gap-2"><button disabled={busy} onClick={()=>void review(row.id,'rejected')} className="rounded-xl border border-rose-200 bg-white px-3 py-2 text-[10px] font-black text-rose-700">ڕەتکردنەوە</button><button disabled={busy} onClick={()=>void review(row.id,'approved')} className="rounded-xl bg-emerald-600 px-3 py-2 text-[10px] font-black text-white">پەسەندکردن</button></div></div>) : <p className="rounded-2xl bg-slate-50 p-6 text-center text-sm font-bold text-slate-500">هیچ داواکارییەکی چاوەڕوان نییە.</p>}</div></section>}
  {noteRole && <div className="fixed inset-0 z-[70] grid place-items-center bg-slate-950/35 p-4 backdrop-blur-sm"><section className="w-full max-w-lg rounded-[28px] bg-white p-6 shadow-2xl"><p className="text-[10px] font-black tracking-[.16em] text-orange-600">ROLE REQUEST</p><h2 className="mt-2 text-2xl font-black">داوای {roles.find((r)=>r[0]===noteRole)?.[1]}</h2><p className="mt-2 text-xs leading-6 text-slate-500">دەتوانیت تێبینییەکی کورت زیاد بکەیت بۆ admin.</p><textarea rows={4} value={note} onChange={(e)=>setNote(e.target.value)} className="mt-4 w-full rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm outline-none focus:border-orange-300" /><div className="mt-4 flex justify-end gap-2"><button className="shakh-ghost-btn" onClick={()=>setNoteRole(null)} type="button">هەڵوەشاندنەوە</button><button className="shakh-btn-primary" disabled={busy} onClick={()=>void apply(noteRole)} type="button">ناردنی داواکاری</button></div></section></div>}
  </main></AppShell>;
}
