create or replace function private.get_captain_mobile_snapshot(p_captain_user_id uuid default null)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private as $$
declare v_target uuid:=coalesce(p_captain_user_id,auth.uid()); v_me uuid:=auth.uid(); v_ops boolean:=private.has_permission('delivery.manage');
begin
 if v_target is null or (v_target<>v_me and not v_ops) then raise exception 'captain_snapshot_forbidden' using errcode='P0001'; end if;
 if not exists(select 1 from public.captain_profiles where user_id=v_target and is_verified=true) then raise exception 'captain_not_found' using errcode='P0001'; end if;
 return jsonb_build_object(
  'captain',(select jsonb_build_object('user_id',cp.user_id,'captain_code',cp.captain_code,'status',cp.status,'vehicle_type',cp.vehicle_type,'vehicle_make',cp.vehicle_make,'vehicle_model',cp.vehicle_model,'vehicle_plate',cp.vehicle_plate,'is_verified',cp.is_verified,'updated_at',cp.updated_at,'last_location',case when cll.latitude is not null and cll.longitude is not null then jsonb_build_object('latitude',cll.latitude,'longitude',cll.longitude,'heading',cll.heading,'speed_kmh',cll.speed_kmh,'accuracy_m',cll.accuracy_m,'recorded_at',cll.recorded_at,'age_seconds',greatest(0,floor(extract(epoch from(clock_timestamp()-cll.recorded_at)))::integer)) else null end) from public.captain_profiles cp left join public.captain_live_locations cll on cll.captain_user_id=cp.user_id where cp.user_id=v_target),
  'active_assignment',(select jsonb_build_object('assignment_id',da.id,'order_id',da.order_id,'order_number',o.order_number,'status',da.status,'estimated_minutes',da.estimated_minutes,'delivery_fee_iqd',da.delivery_fee_iqd,'captain_earning_iqd',da.captain_earning_iqd,'assigned_at',da.assigned_at,'accepted_at',da.accepted_at,'picked_up_at',da.picked_up_at,'buyer_name',o.shipping_recipient_name,'buyer_phone',o.shipping_phone,'shipping_city',o.shipping_city,'shipping_district',o.shipping_district,'shipping_street',o.shipping_street,'shipping_landmark',o.shipping_landmark,'shipping_notes',o.shipping_notes,'vendor_name',v.name_ckb,'vendor_latitude',v.latitude,'vendor_longitude',v.longitude,'pickup',case when da.pickup_latitude is not null and da.pickup_longitude is not null then jsonb_build_object('latitude',da.pickup_latitude,'longitude',da.pickup_longitude) else null end,'dropoff',case when da.dropoff_latitude is not null and da.dropoff_longitude is not null then jsonb_build_object('latitude',da.dropoff_latitude,'longitude',da.dropoff_longitude) else null end,'last_location',case when cll.latitude is not null and cll.longitude is not null then jsonb_build_object('latitude',cll.latitude,'longitude',cll.longitude,'heading',cll.heading,'speed_kmh',cll.speed_kmh,'accuracy_m',cll.accuracy_m,'recorded_at',cll.recorded_at) else null end,'sla',private.get_delivery_sla(o.created_at,da.status,da.assigned_at,da.accepted_at,da.picked_up_at,da.estimated_minutes)) from public.delivery_assignments da join public.orders o on o.id=da.order_id join public.vendors v on v.id=o.vendor_id left join public.captain_live_locations cll on cll.captain_user_id=da.captain_user_id where da.captain_user_id=v_target and da.status in('assigned','accepted','at_pickup','picked_up','out_for_delivery') order by da.updated_at desc limit 1),
  'pending_assignments',coalesce((select jsonb_agg(to_jsonb(q) order by q.assigned_at asc) from(select da.id assignment_id,da.order_id,o.order_number,da.status,da.estimated_minutes,da.assigned_at,v.name_ckb vendor_name,o.shipping_city,o.shipping_district,o.shipping_street,private.get_delivery_sla(o.created_at,da.status,da.assigned_at,da.accepted_at,da.picked_up_at,da.estimated_minutes) sla from public.delivery_assignments da join public.orders o on o.id=da.order_id join public.vendors v on v.id=o.vendor_id where da.captain_user_id=v_target and da.status='assigned' order by da.assigned_at asc limit 5)q),'[]'::jsonb),
  'recent_assignments',coalesce((select jsonb_agg(to_jsonb(q) order by q.updated_at desc) from(select da.id assignment_id,da.order_id,o.order_number,da.status,da.estimated_minutes,da.delivery_fee_iqd,da.captain_earning_iqd,da.updated_at from public.delivery_assignments da join public.orders o on o.id=da.order_id where da.captain_user_id=v_target order by da.updated_at desc limit 10)q),'[]'::jsonb)
 );
end; $$;
create or replace function public.get_captain_mobile_snapshot(p_captain_user_id uuid default null)
returns jsonb language sql security invoker set search_path=pg_catalog,public,private as $$ select private.get_captain_mobile_snapshot(p_captain_user_id); $$;
revoke all on function private.get_captain_mobile_snapshot(uuid) from public,anon,authenticated;
revoke all on function public.get_captain_mobile_snapshot(uuid) from public,anon;
grant execute on function public.get_captain_mobile_snapshot(uuid) to authenticated;
